---
- hosts: localhost
# FIXME https://blog.filador.fr/je-configure-macos-avec-ansible/
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - git
          - vim
