---
# ASDF
asdf_plugins:
  - name: "rust"
    repository: "https://github.com/asdf-community/asdf-rust.git"
    versions:
      - "1.62.0"
    global: "1.62.0"
    yum_deps: []
  - name: "direnv"
    versions: ["2.32.0"]
    global: "2.32.0"
    yum_deps: []
  - name: "fzf"
    versions: ["0.30.0"]
    global: "0.30.0"
    yum_deps: []
  - name: "starship"
    versions: ["1.10.3"]
    global: "1.10.3"
    yum_deps: []

commons_custom_scripts:
  - command: starship
    script: 'eval "$(starship init bash)"'
  - command: npm
    script: "source <(npm completion)"
  - command: kubectl
    script: "source <(kubectl completion bash)"
  - command: aws_completer
    script: "complete -C ~/.asdf/shims/aws_completer aws"
  - command: terraform
    script: 'complete -C $(asdf where terraform)/bin/terraform terraform'
  - command: direnv
    script: 'eval "$(direnv hook bash)"'
  - command: fzf
    script: "source $(asdf where fzf)/shell/key-bindings.bash"
  - command: k3d
    script: "source <(k3d completion bash)"
  - command: argocd
    script: "source <(argocd completion bash)"


asdf_version: "v0.11.3"
asdf_legacy_version_file: "no"

# HOSTNAME
hostname_name: work
hostname_fqdn: work.localhost

# GNOMES EXTENSIONS
gnome_extension_ids: []
# DOCKER
docker_users: ["{{ ansible_user_id }}"]
